### ISSUE TITLE
N/A for summer time use of cattle/pig slurry

### ISSUE THREAD

**Issue by nebogeo** [nebogeo/crapapppro#27]
what should happen here?

**Comment by beckyduchy** [comment]
this is because you aren't incorporating it in the summer as the grass is growing (so you aren't ploughing the field to get the manures into the soil. could we have it so that if you select a date that falls in the summer either soil incorporated isnt an option or just use the ones for surface applied with a star (and an explanation).

**Comment by nebogeo** [comment]
This was kind of confusing, as you get values for P and K - I've displayed this as N/A just to match what RB209 does
